"""Select official Plex WOFF2 subsets; regenerate after font package upgrades."""
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
faces = []
for package in ('plex-sans', 'plex-sans-sc', 'plex-sans-jp'):
    text = (root / f'node_modules/@ibm/{package}/css/ibm-{package}-all.css').read_text()
    for face in re.findall(r'@font-face\s*\{[^}]+\}', text):
        if not re.search(r'font-weight: (400|500|600);', face) or 'font-style: normal;' not in face:
            continue
        if package != 'plex-sans' and 'unicode-range:' not in face:
            continue
        if package == 'plex-sans' and 'unicode-range:' in face:
            continue
        url = re.search(r'url\("([^\"]+\.woff2)"\)', face).group(1)
        url = f'../node_modules/@ibm/{package}/' + url.removeprefix('../')
        face = re.sub(r'  src:.*', f'  src: url("{url}") format("woff2");\n  font-display: swap;', face)
        faces.append(face)
(root / 'src/fonts.css').write_text('/* Generated by scripts/build-font-css.py. IBM Plex, OFL-1.1. */\n' + '\n'.join(faces) + '\n')
